// Simple language helper
function getLang(sock) {
    // Return default English language strings
    return {
        deepseek_failed: '❌ Deepseek API failed. Please try again later.',
        quran_usage: 'Usage: .quran <surah>:<ayah>',
        quran_invalid: 'Invalid format. Use: .quran 1:1',
        quran_not_found: 'Ayah not found. Please check the numbers.',
        quran_error: 'Error fetching Quran verse.',
        catbox_no_media: 'Please reply to an image, video, audio, document, or sticker.',
        catbox_uploading: '⏳ Uploading...',
        catbox_error: '❌ Upload failed. Try again.',
        autoreply_on: '✅ Auto-reply enabled.',
        autoreply_off: '❌ Auto-reply disabled.',
        autoreply_cleared: '🧹 Seen users list cleared.',
        autoreply_reset: '🔄 Auto-reply reset to default message.',
        autoreply_image_removed: '🖼️ Image removed.',
        autoreply_no_image: 'No image attached.',
        autoreply_usage_set: 'Usage: .autoreply set <message>',
        autoreply_set_success: '✅ Auto-reply message set: {msg}',
        autoreply_set_with_image: '✅ Auto-reply message set with image: {msg}',
        autoreply_set_image_failed: '⚠️ Message set but image failed: {msg}',
        autoreply_unknown: 'Unknown subcommand. Use .autoreply for help.',
        chatbot_on: '✅ Chatbot enabled in {mode}.',
        chatbot_off: '❌ Chatbot disabled.',
        chatbot_dm_only: '💬 Chatbot set to DMs only.',
        chatbot_groups_only: '💬 Chatbot set to groups only.',
        chatbot_everywhere: '💬 Chatbot set to everywhere.',
        chatbot_text_mode: '📝 Chatbot reply mode: Text only.',
        chatbot_audio_mode: '🔊 Chatbot reply mode: Audio only.',
        chatbot_both_mode: '📝🔊 Chatbot reply mode: Text + Audio.',
        chatbot_train_usage: 'Usage: .chatbot train <prompt>',
        chatbot_train_success: '✅ AI trained with: {prompt}',
        chatbot_prompt_show: 'Current training: {prompt}',
        chatbot_reset: '🔄 AI training reset to default.',
        chatbot_cleared: '🧹 Chat history cleared.',
        chatbot_unknown: 'Unknown subcommand.',
        btn_turn_on: 'Turn On',
        btn_turn_off: 'Turn Off',
        chatbot_btn_dm: 'DMs',
        chatbot_btn_group: 'Groups',
        chatbot_btn_all: 'All',
        chatbot_btn_text: 'Text',
        chatbot_btn_audio: 'Audio',
        chatbot_btn_both: 'Both',
        chatbot_btn_prompt: 'View Prompt',
        chatbot_btn_clear: 'Clear History',
    };
}

module.exports = { getLang };